[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python startup.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = {}
PORT = "8000"
