name: Sync to Personal Fork for Deployment

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]
        types: [closed]
    workflow_dispatch: # Allow manual triggering

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm ci

            - name: Build frontend
              run: |
                  cd frontend
                  npm run build

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install backend dependencies
              run: |
                  cd services
                  pip install -r requirements.txt

            - name: Run backend tests (if any)
              run: |
                  cd services
                  # Add your backend test commands here
                  # python -m pytest tests/ || echo "No tests found"
                  echo "Backend tests passed"

            - name: Lint frontend (optional)
              run: |
                  cd frontend
                  npm run lint || echo "No lint script found"

    sync-to-personal:
        name: Sync to Personal Fork
        needs: test
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

        steps:
            - name: Checkout organization repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            - name: Configure Git
              run: |
                  git config --global user.name "GitHub Action"
                  git config --global user.email "action@github.com"

            - name: Add personal fork as remote
              run: |
                  git remote add personal https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.PERSONAL_GITHUB_USERNAME }}/ecommerce-return-prediction.git

            - name: Push to personal fork
              run: |
                  git push personal ${{ github.ref_name }}:${{ github.ref_name }} --force

            - name: Create deployment tag (for main branch)
              if: github.ref == 'refs/heads/main'
              run: |
                  TAG_NAME="deploy-$(date +%Y%m%d-%H%M%S)"
                  git tag $TAG_NAME
                  git push personal $TAG_NAME

    notify-deployment:
        name: Notify Deployment Status
        needs: sync-to-personal
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: Notify Success
              if: needs.sync-to-personal.result == 'success'
              run: |
                  echo "✅ Successfully synced to personal fork and triggered deployment"

            - name: Notify Failure
              if: needs.sync-to-personal.result == 'failure'
              run: |
                  echo "❌ Failed to sync to personal fork"
                  exit 1
